# Change to you app name before deploying
app = "nazurin"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  # Alternatively, you may use "yyoung01/nazurin:latest"
  image = "ghcr.io/y-young/nazurin:latest"

[env]
  PORT = 8080

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
