name: "Python-lint-annotate: maintain code quality with annotated PRs and pushes"
description: "Zero-configuration GitHub Action to maintain code quality with push and PR annotations."
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  python-root-list:
    description: "A list of all paths to test"
    required: false
    default: "."
  extra-pylint-options:
    description: "Extra options: pylint $(extra-pylint-options) $(python-root-list)"
    required: false
    default: ""
  pylint-version:
    description: "Set desired pylint version with this keyword"
    required: false
    default: "2.16.1"

runs:
  using: "composite"
  steps:
    - name: Windows install pylint
      if: ${{ runner.os == 'Windows' }}
      run: |
        echo "::group::Install pylint"
        pip install pylint==${{ inputs.pylint-version }}
        echo "path_sep=" >> $GITHUB_ENV
        echo "::endgroup::"
      shell: pwsh

    - name: Posix install pylint
      if: ${{ runner.os != 'Windows' }}
      run: |
        echo "::group::Install pylint"
        pip install pylint==${{ inputs.pylint-version }}
        echo "::endgroup::"
      shell: bash

    - name: Lint on Windows
      if: ${{ runner.os == 'Windows' }}
      run: >
        ${{ github.action_path }}\entrypoint.sh
        '${{ inputs.python-root-list }}'
        '${{ inputs.extra-pylint-options }}'
      shell: pwsh

    - name: Lint on Linux
      if: ${{ runner.os == 'Linux' }}
      run: >
        ${{ github.action_path }}/entrypoint.sh
        '${{ inputs.python-root-list }}'
        '${{ inputs.extra-pylint-options }}'
      shell: bash
