name: Pylint

on:
  push:
    branches: [master]
    paths:
      - "nazurin/**"
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches: [master]
    paths:
      - "nazurin/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          echo "::group::Install pip"
          python -m pip install --upgrade pip
          echo "::endgroup::"
          echo "::group::Install dependencies"
          pip install -r requirements.txt
          echo "::endgroup::"
      - name: Lint
        uses: ./.github/actions/pylint
        with:
          python-root-list: ./nazurin
          extra-pylint-options: --fail-on=F,E --fail-under=9.5
